### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by jorampic** [velbus/velbus-tcp-snap#1]
Dear, if I want to install the software on a new installation of Debian (Debian GNU/Linux 9 \n \l
) then string in the following failure :

root @ velbusipserialserver: / home / jorampic # snap install velbus-tcp
error: cannot perform the following tasks:
- Run configure hook or "velbus-tcp" snap if present (run hook "configure": Given TCP port '[' ']' is not an integer)
root @ velbusipserialserver: / home / jorampic #

**Comment by dukeofphilberg** [comment]
Can't replicate this on an Ubuntu 18.10, will check with a Debian VM

**Comment by dukeofphilberg** [comment]
Hi @jorampic 

It seems the core snap isn't automatically installed in debian, issue a `snap install core` first, then retry.

Refer to this issue: https://github.com/ubuntu/microk8s/issues/156
