### ISSUE TITLE
Version installed is still 1.5.1

### ISSUE THREAD

**Issue by JornHermans** [velbus/velbus-tcp-snap#13]
Hello,

When i install this package, it is still installing version 1.5.1

`velbus-tcp 1.5.1 from Velbus installed`

Can you push the updates to snapd?

Greetings

**Comment by dukeofphilberg** [comment]
Hi,

You can change the channel to get an update. The candidate channel currently follows version 1.6.1 and edge has version 2.0.0 which is built on core22. We'll look to promote these versions to the stable channels sometime soon.

```
$ snap info velbus-tcp
name:      velbus-tcp
summary:   Python application that bridges a Velbus installation with TCP
publisher: Velbus
store-url: https://snapcraft.io/velbus-tcp
license:   unset
description: |
  Python application that bridges a Velbus installation with TCP.
snap-id: rpDMnYgUItFJyW7gzEFtYHPu2BlGgw2z
channels:
  latest/stable:    1.5.1 2022-01-06 (136) 11MB -
  latest/candidate: 1.6.1 2023-12-06 (148) 11MB -
  latest/beta:      ↑
  latest/edge:      2.0.0 2023-12-06 (159)  6MB -
```

**Comment by JornHermans** [comment]
> Hi,
> 
> 
> 
> You can change the channel to get an update. The candidate channel currently follows version 1.6.1 and edge has version 2.0.0 which is built on core22. We'll look to promote these versions to the stable channels sometime soon.
> 
> 
> 
> ```
> 
> $ snap info velbus-tcp
> 
> name:      velbus-tcp
> 
> summary:   Python application that bridges a Velbus installation with TCP
> 
> publisher: Velbus
> 
> store-url: https://snapcraft.io/velbus-tcp
> 
> license:   unset
> 
> description: |
> 
>   Python application that bridges a Velbus installation with TCP.
> 
> snap-id: rpDMnYgUItFJyW7gzEFtYHPu2BlGgw2z
> 
> channels:
> 
>   latest/stable:    1.5.1 2022-01-06 (136) 11MB -
> 
>   latest/candidate: 1.6.1 2023-12-06 (148) 11MB -
> 
>   latest/beta:      ↑
> 
>   latest/edge:      2.0.0 2023-12-06 (159)  6MB -
> 
> ```
> 
> 
> 
> 

So as i understand this version 2.0.0 is even more current then the python git? 
Or is this only the core22 change?

**Comment by dukeofphilberg** [comment]
> > Hi,
> > You can change the channel to get an update. The candidate channel currently follows version 1.6.1 and edge has version 2.0.0 which is built on core22. We'll look to promote these versions to the stable channels sometime soon.
> > ```
> > 
> > $ snap info velbus-tcp
> > 
> > name:      velbus-tcp
> > 
> > summary:   Python application that bridges a Velbus installation with TCP
> > 
> > publisher: Velbus
> > 
> > store-url: https://snapcraft.io/velbus-tcp
> > 
> > license:   unset
> > 
> > description: |
> > 
> >   Python application that bridges a Velbus installation with TCP.
> > 
> > snap-id: rpDMnYgUItFJyW7gzEFtYHPu2BlGgw2z
> > 
> > channels:
> > 
> >   latest/stable:    1.5.1 2022-01-06 (136) 11MB -
> > 
> >   latest/candidate: 1.6.1 2023-12-06 (148) 11MB -
> > 
> >   latest/beta:      ↑
> > 
> >   latest/edge:      2.0.0 2023-12-06 (159)  6MB -
> > ```
> 
> So as i understand this version 2.0.0 is even more current then the python git? Or is this only the core22 change?

It follows python-velbustcp 1.6.1 but targets core22. We'll look to change the snap version to 1.6.1 but with core22.
