### ISSUE TITLE
Can't connect with VelbusLink

### ISSUE THREAD

**Issue by JornHermans** [velbus/velbus-tcp-snap#2]
When no authorization is set i can connect with succes using VelbusLink, when authorization is set VelbusLink does not ask after a AuthKey so no connection can be setup.

**Comment by JornHermans** [comment]
**Is this issue being looked at?**

**Comment by dukeofphilberg** [comment]
Authorization through auth key is currently not supported in VelbusLink, it will be at a later date. For now you will have to disable it.
