### ISSUE TITLE
High CPU and Memory Usage

### ISSUE THREAD

**Issue by JornHermans** [velbus/velbus-tcp-snap#4]
I have noticed on several instances (4x) an increase of the CPU and Memory Usage.
Before we made use of the velserv.arm package and did not encounter this.

![cpuusaage](https://user-images.githubusercontent.com/34610908/98439686-dc4b5b80-20f3-11eb-84db-64b6537ee6b3.png)

**Comment by JornHermans** [comment]
High CPU Usage can be resolved by restarting the SNAP every 1 hour.

**Comment by dukeofphilberg** [comment]
We can't currently reproduce this, following is our top output
![image](https://user-images.githubusercontent.com/26272906/98556751-afd64180-22a3-11eb-9a87-4433b738bf47.png)

We'll further look into this, thanks for the report

**Comment by JornHermans** [comment]
Also to add... when i restart the snap the memory clears up, updated now to latest version will report back with results
